resources:
  - name: pipeline-repo
    type: git
    source:
      uri: https://github.com/JaydenLiang/concourse-pipelines.git
      branch: develop

jobs:
  - name: demo
    public: true
    plan:
      - get: pipeline-repo
      - task: fetch-demo-inputs
        file: pipeline-repo/resources/demo-inputs.yml
      - task: create-demo-outputs
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: busybox }
          inputs:
            - name: pipeline-repo
          outputs:
            - name: demo_outputs
          run:
            path: pipeline-repo/scripts/demo_outputs.sh
      - task: show-demo-outputs
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: busybox }
          inputs:
            - name: pipeline-repo
            - name: demo_outputs
          run:
            path: cat
            args: [demo_outputs/default]
